- name: Add user to CentOS
  hosts: CentOS
  become: true
  tasks:
  - name: Create a user
    user:
      name: admin
      groups: wheel

  - name: Add SSH key
    authorized_key:
      user: admin
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINRU7hMEVE7sGlgXomTl23caimQ2T4XujRPplFA1Lpmc Ansible"

  - name: Add sudoers file for admin
    copy:
      src: sudoer_admin
      dest: /etc/sudoers.d/admin
      owner: root
      group: wheel
      mode: 0440
