- name: Install and configure Apache on CentOS 7
  hosts: all
  become: true
  tasks:
  - name: Install Apache
    yum:
      name: httpd
      state: present

  - name: Add Apache service to firewall
    firewalld:
      service: http
      permanent: yes
      state: enabled
      immediate: yes

  - name: Reload firewall
    service:
      name: firewalld
      state: reloaded

  - name: Start Apache service
    service:
      name: httpd
      state: started
