- name: Install and configure Apache on CentOS 7
  hosts: all
  become: true
  tasks:
  - name: Update repository index
    yum:
      update_cache: yes

  - name: Install Apache, PHP and its' modules
    yum:
      name:
      - php
      - php-mysql
      - httpd
      state: present

  - name: Add Apache service to firewall
    firewalld:
      service: http
      permanent: yes
      state: enabled
      immediate: yes

  - name: Reload firewall
    service:
      name: firewalld
      state: reloaded

  - name: Start Apache service
    service:
      name: httpd
      state: started
