- name: Install and configure Apache on CentOS 7
  hosts: CentOS
  become: true
  tasks:
  - name: Update repository index
    package:
      update_cache: yes

  - name: Install Apache, PHP and its' modules
    package:
      name:
      - "{{ apache_package }}"
      - "{{ php_package }}"
      - "{{ php_sql_module }}"
      state: present

  - name: Add Apache service to firewall
    firewalld:
      service: http
      permanent: yes
      state: enabled
      immediate: yes

  - name: Reload firewall
    service:
      name: firewalld
      state: reloaded

  - name: Start Apache service
    service:
      name: httpd
      state: started
