- name: Push file to /var/www/html/
  hosts: CentOS
  become: true
  tasks:
  - name: Push the file
    copy:
      src: push_me.txt
      dest: /var/www/html/push_me.txt
      owner: root
      group: root
      mode: 0644
